### ISSUE TITLE
Account for sentences ending in ! and ? and for blanks in get_average_sentence_length()

### ISSUE THREAD

**Issue by karl-project-review** [sergeprep/forcode#1]
https://github.com/sergeprep/forcode/blob/908f0a6d1746b3cda38e101878c44f7613eb8477/Murder%2BMystery.py#L50-L67
In the get_average_sentence_length() function, we need to account for sentences ending in exclamation points and question marks, instead of only sentences ending in periods. We can do so by using the replace() function to convert these other punctuation marks into periods. 

Also, the call to .split('.') inserts an extra, blank "sentence" at the end of sentences_in_text due to the final period, so we must be sure to remove or otherwise account for this blank, as it is currently treated as a sentence of length zero, which throws off our averages. 

Finally, try to avoid leaving unused code in the functions, such as the split_sent variable, which is initialized, filled with values in the loop, but then not actually used in the computations of the average. 

Below is an example of a revised version of your function which fixes all of the problems mentioned above.
```python
def get_average_sentence_length(text):
    all_periods = text.replace("!", ".").replace("?", ".")
    sentences_in_text = all_periods.split('.')[:-1] #this removes the blank at the end
    num_sentences_in_text = len(sentences_in_text)
    tot_words = 0
    for sentence in sentences_in_text:
        sentence_length = len(sentence.split())
        tot_words += sentence_length  
    avg = (tot_words / num_sentences_in_text)
    return avg
```

**Comment by sergeprep** [comment]
Put the additional sentences ending with ! ? and remove the last .
