### ISSUE TITLE
Account for case where table2[key] <= table1[key] in frequency_comparison()

### ISSUE THREAD

**Issue by karl-project-review** [sergeprep/forcode#2]
https://github.com/sergeprep/forcode/blob/908f0a6d1746b3cda38e101878c44f7613eb8477/Murder%2BMystery.py#L101-L106
Note that currently the frequency_comparison() function disregards cases where a word appears in both tables but either appears the same number of times in both or more in table1 than in table2. We can fix this by adding an else clause, as shown below (note that we can deal with the case where table1[key] == table2[key] by grouping it with either the table1[key] > table2[key] case or the table1[key] < table2[key] case, since it doesn't matter which one we add to appearances and mutual_appearances if these values are equal):
```python
if key in table2.keys(): 
    if table2[key] > table1[key]: 
        mutual_appearances += table1[key] 
        appearances += table2[key]
    else:
        mutual_appearances += table2[key]
        appearances += table1[key] 
else: 
    appearances += table1[key] 
```

**Comment by sergeprep** [comment]
Incorporated  changes in Frequency_comparison() function
