### ISSUE TITLE
find_similarity_score() should return the average of the three similarity scores

### ISSUE THREAD

**Issue by karl-project-review** [sergeprep/forcode#3]
https://github.com/sergeprep/forcode/blob/908f0a6d1746b3cda38e101878c44f7613eb8477/Murder%2BMystery.py#L277-L288
Currently, the find_similarity_score() function does not return anything. However, it should return the average of the sentence_length_similarity, word_count_similarity, and ngram_similarity scores. This can be fixed by finding the sum of these scores, dividing that sum by 3, and returning the resulting value.

**Comment by sergeprep** [comment]
Incorporated the resulting average as indicated.
