### ISSUE TITLE
Similarity score print statements could be refactored into a loop

### ISSUE THREAD

**Issue by karl-project-review** [sergeprep/forcode#4]
https://github.com/sergeprep/forcode/blob/908f0a6d1746b3cda38e101878c44f7613eb8477/Murder%2BMystery.py#L301-L306
In an effort to avoid having too much repeated code, we could use a for loop to handle these print statements, as demonstrated here:
```python
samples = [lily_sample, myrtle_sample, gregg_sample]
for sample in samples:
    print(sample.author,"similarity score to the murderer's letter") 
    find_text_similarity(murderer_sample, sample) 
```

**Comment by sergeprep** [comment]
Added to my Code as such (with extra blank line for clarity)
samples = [lily_sample, myrtle_sample, gregg_sample]
for sample in samples:
    print("\n",sample.author,"similarity score to the murderer's letter") 
    print ("Average Similarities :",find_text_similarity(murderer_sample, sample))
