### ISSUE TITLE
Murder Mystery Summary & Rubric Score

### ISSUE THREAD

**Issue by karl-project-review** [sergeprep/forcode#5]
### Criteria 1: Valid Python Code
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ Your code runs without throwing any errors. Well done!
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ You implemented versions of all the required functions and the TextSample class.
### Criteria 3: Software Architecture
* _Score Level:_ 3/4 (Meets Expectations)
* _Comment(s):_ Most of your code is grouped into functions and loops appropriately. However, as noted in issue #4, the print statements in lines 301-306 could be refactored into a loop to avoid repeating code. 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ You consistently used Python language features where appropriate.
### Criteria 5: Produces Accurate Output
* _Score Level:_ 2/4 (Approaches Expectations)
* _Comment(s):_ There were problems with the get_average_sentence_length() and frequency_comparison() functions that result in the similarity scores being off and the wrong suspect being identified. These problems are described in issues #1 and #2. Also, as noted in issue #3, the find_text_similarity() function should return the average of the individual similarity scores, which should then be printed.
### Overall Score: 17/20 (Meets Expectations)
Nice job! The majority of your code does what it should, and you clearly tested many of your functions (judging from the included print statements), which is a crucial part of software development. My primary recommendation for you moving forward is to make sure that your functions account for all relevant cases that might come up. For example, accounting for exclamation points and question marks as sentence endings (see issue #1), or accounting for the case of equality as well as the different kinds of inequality when comparing values (see issue #2). Thinking through these possible cases and testing to make sure our code deals with them appropriately makes our functions more robust and prevents unexpected errors in our calculations. Again, well done!

**Comment by sergeprep** [comment]
Thank You for the Review. I have gone over each of the 5 issues and incorporated them in my code. Your review is concise and clear.
